### ISSUE TITLE
The question of task efficiency

### ISSUE THREAD

**Issue by dd-rongfa** [Ber666/RAP#2]
How many times does the agent need to communicate with the LLM to complete the   task? or provide an estimated range？
（平均每个任务大概需要交互多少次？ 有大概范围么）

**Comment by Ber666** [comment]
Hi, the number of interactions is basically the same as the reasoning step number in CoT, e.g. for Blocksworld, it depends on the steps needed to solve the problem (2/4/6 in our experiments), and for the other two reasoning tasks, it should be about 3-6 steps.
