### ISSUE TITLE
Some bugs in the code

### ISSUE THREAD

**Issue by shuqike** [Ber666/RAP#3]
There are some bugs in the code. For example,
1. In run_blocksworld.py, line 18, it shouldn't be "from rap.models import WorldModel, AgentModel, QueryLlama". It should be "from rap.models import QueryLlama".
2. In run_blocksworld.py, line 200&204, the function call "instance_to_text_blocksworld" is only defined in the beta branch (https://github.com/karthikv792/LLMs-Planning/tree/latest-beta). And its definition actually changed. It no longer returns three values (INIT GOAL PLAN) but four (INIT GOAL PLAN and data). Can you guys explicitly mention in your README.md that the users should use the beta branch? It would be helpful to other people. Actually, it would be good if you guys can just clone those files into your repo because nobody knows how karthikv792 will update his code in the future. Just a few steps could benefit a lot of scholars trying to reproduce your results. Thanks!

**Comment by Ber666** [comment]
Fixed. Thanks for your advice!
