### ISSUE TITLE
"Prior" option in MCTS

### ISSUE THREAD

**Issue by jiadingfang** [Ber666/RAP#5]
Hi, thanks for the great work and previous help on running the scripts.

I'm looking into the code to understand how it exactly runs for each game. I noticed that, the parameters for calling MCTS all include an option called "prior" and are set to True by default for all 3 games, e.g. 
`mcts = MCTS(w_exp=w_exp, prior=True, aggr_reward='mean', aggr_child='max')`
The option "prior" is used to turn on or off the following logic:
```
if self.prior:
    path = self._select_prior(node)
else:
    path = self._select(node)
    self._expand(path[-1])
    self._simulate(path)
```
I'm not exactly sure what's the difference between the two as the paper only talks about the 4-stage "select-->expand-->simulate-->back-propagate" logic. I also did some experiments, with "prior" option on, the success rate is higher compare to turning off "prior" option.

Highly appreciate if you could explain a bit about this design, thanks in advance!

**Comment by wu-qing-157** [comment]
`prior=True` corresponds to "picking one of the largest local reward" in the expansion and simulation phase mentioned in the paper. `prior=False` means choosing a random unexplored child if there exists any, which is a more classical setting in MCTS.

We find that `prior=True` can increase the efficiency of the search with a limited number of step, so we use this setting for all 3 tasks.

In `_select_prior`, we actually are treating Q-value for visited nodes and local reward for unvisited node as almost the same, and there is only slight difference across the first three stages. So we includes selection, expansion, and simulation phases in this single function. I acknowledge that the naming may not be the best to describe this function.
