### ISSUE TITLE
Selection of The Demonstration Examples

### ISSUE THREAD

**Issue by artpli** [Ber666/RAP#9]
Dear authors, thank you for your great work!

I have a question here: 
According to my experiments, I found that the demonstration examples of the blockworld task were very good and if I changed them with other demo examples, there were always errors when applying the predicted changes to the current states.
Could you please elaborate on how you selected these sample instances?
Thank you very much!

Best,
Peng

**Comment by Ber666** [comment]
Hi, it's indeed not trivial to predict the state change, so we applied different prompts for different actions ([here](https://github.com/Ber666/RAP/blob/774817c228b3d5ddfc18de2318f3476128ecf6eb/rap/blocksworld_mcts.py#L214)). This is a workaround solution given the limited capability Llama-33b, and we expect stronger LLMs can serve as a better world model.

**Comment by artpli** [comment]
@Ber666 I see, thank you for your prompt response!
